### ISSUE TITLE
[BUG] Nvidia GPU acceleration - Blank screens on browser workspaces

### ISSUE THREAD

**Issue by amberflag48** [linuxserver/docker-kasm#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm getting a blank screen when opening browser workspaces with my GPU selected at setup time.

After digging a bit, I can see this error in Kasm: 
`There was an exception running nvidia-smi on agent: (400 Client Error for http+docker://localhost/v1.42/containers/3b3839ffb3839d7501bae85a07312028a42aaecb80af24b5dda90abf4803ece0/start: Bad Request ("failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy' nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown"))`

So I tried spinning the CUDA docker with the nvidia-smi command inside the Kasm container and I'm getting this:
`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.`

The CUDA Docker works just fine when ran directly on the host.

Obviously, the Kasm container can't communicate properly with my GPU. I want to precise that I have other Docker containers using my GPU just fine from you, such as Emby.

Do I need to add `runtime: nvidia` in my compose like I do with Emby?

Thank you for your help!

### Expected Behavior

GPU acceleration should just work like it does with other containers on the same host.

### Steps To Reproduce

1. Start Kasm: `sudo docker compose up -d`
2. Go to Kasm Workspace and try to launch a web browser.
3. I just get a blank page and the above described errors.

### Environment

```markdown
- OS: Debian 11
- How docker service was installed: From the official Docker PPA.
- GPU: Nvidia Quadro P4000
```

### CPU architecture

x86-64

### Docker creation

```bash
kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: 'kasm'
    privileged: true
    environment:
      - 'NVIDIA_VISIBLE_DEVICES=all'
      - 'NVIDIA_DRIVER_CAPABILITIES=all'
      - 'KASM_PORT=3843'
    volumes:
      - 'Kasm/opt:/opt'
      - 'Kasm/profiles:/profiles
    ports:
      - '3141:3000'
      - '3843:3843'
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
time="2023-04-05T06:33:12.740317723Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
time="2023-04-05T06:33:14.333560075Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-05T06:33:14.333728582Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-05T06:33:14.333769388Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-05T06:33:14.334245694Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/a770b4826677a0ca4683f4bef9f6a3155144f64b8936098fe4dc87baf5eff0f5 pid=564 runtime=io.containerd.runc.v2
time="2023-04-05T06:33:14.434022059Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-05T06:33:14.434164382Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-05T06:33:14.434196132Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-05T06:33:14.434576959Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/5921496d47a89290b3f37f49770ad135e41dd476c321e37f1660f9f0e0b1a2a0 pid=614 runtime=io.containerd.runc.v2
time="2023-04-05T06:33:14.593325566Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-05T06:33:14.593384083Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-05T06:33:14.593396932Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-05T06:33:14.593559100Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/5eb306eb4b1b760a0abd3510ee5ee4cc849a436e480273a7a97372b5640bdf7e pid=747 runtime=io.containerd.runc.v2
time="2023-04-05T06:33:14.598603011Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-05T06:33:14.598658823Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-05T06:33:14.598671226Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-05T06:33:14.599077177Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/1f917c68c0d40861bca1864ad312b8113c0e65d84cd26681d66578710370aa64 pid=763 runtime=io.containerd.runc.v2
time="2023-04-05T06:33:14.708158962Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-05T06:33:14.708292438Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-05T06:33:14.708318278Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-05T06:33:14.708651669Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/204932cb2a09c0b29da51849f3877f1569de1804f9bfc2765d345f57509b0dbb pid=879 runtime=io.containerd.runc.v2
time="2023-04-05T06:33:14.759442993Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-05T06:33:14.759584967Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-05T06:33:14.759624310Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-05T06:33:14.760137402Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/f1aabd8c2063795923893244babe6a13fbd93cde8e59f0c3cd1cc4d80f0f67c1 pid=948 runtime=io.containerd.runc.v2
time="2023-04-05T06:33:14.828114025Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-05T06:33:14.828227315Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-05T06:33:14.828277878Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-05T06:33:14.828595416Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/86827b24ab4bf2e2ed7b545a545f59093cf6b3c8278f5e86c200d21fd050a7a0 pid=1060 runtime=io.containerd.runc.v2
time="2023-04-05T06:33:15.060361963Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-05T06:33:15.060463371Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-05T06:33:15.060485962Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-05T06:33:15.060710206Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/b21d90dca1aa5d2690ab3235cc08bece7aa6833d88735d29a743d8f89875c764 pid=1344 runtime=io.containerd.runc.v2
time="2023-04-05T06:33:15.062738049Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-05T06:33:15.062795979Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-05T06:33:15.062806788Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-05T06:33:15.062932107Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/6e682dffac5b2eea56fa86169ed760dc8e2010fd31961d592219a5fe8a290854 pid=1346 runtime=io.containerd.runc.v2
time="2023-04-05T06:33:18.607433335Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-05T06:33:18.607561199Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-05T06:33:18.607597822Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-05T06:33:18.607895899Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/3b3839ffb3839d7501bae85a07312028a42aaecb80af24b5dda90abf4803ece0 pid=2160 runtime=io.containerd.runc.v2
time="2023-04-05T06:33:18.821959308Z" level=error msg="copy shim log" error="read /proc/self/fd/50: file already closed"
time="2023-04-05T06:33:18.822670736Z" level=error msg="stream copy error: reading from a closed fifo"
time="2023-04-05T06:33:18.822710100Z" level=error msg="stream copy error: reading from a closed fifo"
time="2023-04-05T06:33:18.970395249Z" level=error msg="3b3839ffb3839d7501bae85a07312028a42aaecb80af24b5dda90abf4803ece0 cleanup: failed to delete container from containerd: no such container"
time="2023-04-05T06:33:26.701291030Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-05T06:33:26.701409823Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-05T06:33:26.701440186Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-05T06:33:26.701854029Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/a472b3c44b06a0528c25d2f8c4523aa8dfd0f10440ee3cd974f4daf09f5383c9 pid=2438 runtime=io.containerd.runc.v2
```

**Comment by thelamer** [comment]
You need to pass gpus all with run that is a simple run flag `--gpus all` but with compose it is a bit more complex: 
https://docs.docker.com/compose/gpu-support/

**Comment by fliptrocity** [comment]
Having this exact issue with a 1050ti. 

Docker-compose as follows 

`kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: 'kasm'
    privileged: true
    environment:
      - 'NVIDIA_VISIBLE_DEVICES=all'
      - 'NVIDIA_DRIVER_CAPABILITIES=all'
      - 'KASM_PORT=443'
    volumes:
      - 'Kasm/opt:/opt'
      - 'Kasm/profiles:/profiles
    ports:
      - '32423:3000'
      - '23424:443'
    restart: unless-stopped`

Can't launch Chrome or Retroarch workspaces . 

I've read some of the other similar issues and none of the solutions for other work for me - GPU works fine in other containers outside of Kasm. Not sure what I might be doing wrong at this point.

**Comment by thelamer** [comment]
For compose it is not just the environment, it depends on your nvidia container runtime config (as all containers can be forced to use  it by default) But the actual syntax for converting the run `--gpus=all` is different in compose IE: 
```
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

So specifically in your case: 

```
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: Kasm
    privileged: true
    environment:
      - KASM_PORT=443
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /Kasm/opt:/opt
      - /Kasm/profiles:/profiles #optional
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 32423:3000
      - 32424:443
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

(this assumes you have 1 NVIDIA GPU on your system)

**Comment by Fabiettus** [comment]
Same here, gpu won't work: 
- installed kasm with firefox, chrome, and terminal workspaces using wizard;
- selected "/dev/dri/card1 - Nvidia DRM driver" on "use GPU on all images"; 
- nvidia gpu is correctly passed through the container ( i can launch nvidia-smi in a container shell);
- Docker Agents under Admin/Compute show 1 GPU; 
but when i launch a workspace i get this error:
```
host: 357568fc55b9
ingest_date: 202305080723
application: kasm_api
levelname: ERROR
kasm_user_name: admin@kasm.local
message: Error during Create request for Server(91dbde83-4701-4590-bd76-c6c1e6cd8dc9) : (Exception creating Kasm: Traceback (most recent call last): File "docker/api/client.py", line 268, in _raise_for_status File "requests/models.py", line 1021, in raise_for_status requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.42/containers/fdaeadb254dcd06ab4f6450e1f79b5b007262ef10cb6fecd40a6c7bcb50a223d/start During handling of the above exception, another exception occurred: Traceback (most recent call last): File "__init__.py", line 538, in post File "provision.py", line 1134, in provision File "docker/models/containers.py", line 818, in run File "docker/models/containers.py", line 404, in start File "docker/utils/decorators.py", line 19, in wrapped File "docker/api/container.py", line 1111, in start File "docker/api/client.py", line 270, in _raise_for_status File "docker/errors.py", line 31, in create_api_error_from_http_exception docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.42/containers/fdaeadb254dcd06ab4f6450e1f79b5b007262ef10cb6fecd40a6c7bcb50a223d/start: Internal Server Error ("error gathering device information while adding custom device "/dev/dri/renderD129": no such file or directory") )
process: client_api_server
client_ip: 10.0.0.90
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
```

 Found that only "/dev/dri/renderD128" is present, even if "/dev/card0" and "/dev/card1" exists (card0 is standard qemu vga i suppose)

**My docker compose is:**
```
version: "3.8"
services:
  kasm:
    image: linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=4443
      - TZ=Europe/Rome
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
         devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    volumes:
      - /home/kasm/opt:/opt
      - /home/kasm/profiles:/profiles #optional
      - /home/kasm/dev/input:/dev/input #optional
      - /home/kasm/run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 4443:4443
    restart: unless-stopped
```

**Docker Run Config Override (JSON) in chrome workspace:**
```
{
  "device_requests": [
    {
      "capabilities": [
        [
          "gpu"
        ]
      ],
      "count": -1,
      "device_ids": null,
      "driver": "",
      "options": {}
    }
  ],
  "devices": [
    "/dev/dri/card1:/dev/dri/card1:rwm",
    "/dev/dri/renderD128:/dev/dri/renderD128:rwm"
  ],
  "environment": {
    "KASM_EGL_CARD": "/dev/dri/card1",
    "KASM_RENDERD": "/dev/dri/renderD128"
  },
  "hostname": "kasm"
}
```


**Docker Exec Config (JSON)**
```
  },
  "first_launch": {
    "cmd": "bash -c 'chown -R kasm-user:kasm-user /dev/dri/*'",
    "user": "root"
  },
  "go": {
    "cmd": "bash -c '/dockerstartup/custom_startup.sh --go --url \"$KASM_URL\"'"
  }
}
```

**Comment by thelamer** [comment]
@Fabiettus the error is pretty clear it says /dev/dri/renderD129 does not exist. I am unsure why that would have been picked up at install time but then be missing during runtime, but what is actually in the container? 

`docker exec kasm ls -l /dev/dri`

**Comment by Fabiettus** [comment]
"docker exec kasm ls -l /dev/dri"
```
root@b460ff99007d:/# ls -l /dev/dri
total 0
crw-rw---- 1 root      video 226,   0 May 10 08:02 card0
crw-rw---- 1 dockremap video 226,   1 May 10 08:02 card1
crw-rw---- 1 dockremap   109 226, 128 May 10 08:02 renderD128
```
"ls -l /sys/class/drm/renderD*/device/driver | awk '{print $9,$11}'"

`/sys/class/drm/renderD128/device/driver ../../../../bus/pci/drivers/nvidia`

You are right,  the error is pretty clear but i can't have gpu working . If i modify renderD129 to renderD128 the result is blank screen

Here the gpu info in Kasm Agent:
```
"deviceId":0
"display_active":"Disabled"
"display_mode":"Enabled"
"driver_version":"530.41.03"
"gpu_card_path":"/dev/dri/card1"
"gpu_render_path":"/dev/dri/renderD128"
"gpu_tempurature":26
"gpu_utilization":0
"memory_free":6070
"memory_total":6144
"memory_used":2
"model":"NVIDIA GeForce GTX 1060 6GB"
"name":"NVIDIA GeForce GTX 1060 6GB"
"pci_bus_id":"0000:01:00.0"
"serial_number":"[N/A]"
"uuid":"GPU-7efb7f97-577a-124a-862d-7a967c538747"
"vendor":"NVIDIA"
```
