### ISSUE TITLE
[BUG] Unable to open workspace web ui on Oracle ARM

### ISSUE THREAD

**Issue by red-avtovo** [linuxserver/docker-kasm#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to run Kasm on Oracle ARM instance

After the the initial setup, I can open the web UI
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/10682826/230598789-54169295-3c0e-4c4b-97ca-cafaa4a326ad.png">

By clicking the the web UI link I see the connection error page
<img width="827" alt="image" src="https://user-images.githubusercontent.com/10682826/230599155-1b18d608-f6ba-4d74-9793-c78cc57fa0a7.png">

### Expected Behavior

Web UI successfully opened

### Steps To Reproduce

- Create container
- Finish the initialization on https://localhost:3000
- Try to open https://localhost:8443

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS
- How docker service was installed:
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \\n  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

### CPU architecture

arm64

### Docker creation

```bash
docker run -d \
    --name=kasm \
    --privileged \
    -e KASM_PORT=8443 \
    -p 3000:3000 \
    -p 8443:8443 \
    -v $HOME/kasm/data:/opt \
    -v $HOME/kasm/profiles:/profiles \
    --restart unless-stopped \
    lscr.io/linuxserver/kasm:latest
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
time="2023-04-07T11:08:50.423947566Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
time="2023-04-07T11:08:51.956633514Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-07T11:08:51.956702874Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-07T11:08:51.956713194Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-07T11:08:51.956974114Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/740ffd0c2326978fef68f1d899fe66b2cd52c952ad6b7f7ddafac3ed62bdfab6 pid=502 runtime=io.containerd.runc.v2
time="2023-04-07T11:08:52.112205005Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-07T11:08:52.112294285Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-07T11:08:52.112306126Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-07T11:08:52.112806967Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/e9e472ddee7c00691942da7a2e4c1815bcf412437424e2ed88c0e4fe6a879a03 pid=563 runtime=io.containerd.runc.v2
time="2023-04-07T11:08:52.116909295Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-07T11:08:52.116963775Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-07T11:08:52.116973775Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-07T11:08:52.117645217Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/894d67e44469fe1f7bce83d15fd190a4fc7576e2867ce5c127b0e53bcb358e03 pid=575 runtime=io.containerd.runc.v2
time="2023-04-07T11:08:52.258329157Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-07T11:08:52.258406197Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-07T11:08:52.258416877Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-07T11:08:52.259400879Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/208f1f51bc392bbf56babff060fdcfc4668311da1c0dccce4bcdae5c817fc4f9 pid=673 runtime=io.containerd.runc.v2
time="2023-04-07T11:08:52.280271284Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-07T11:08:52.280342884Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-07T11:08:52.280352844Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-07T11:08:52.280900525Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/a7bb7f9f4ff9be9119ac927b1221ab06d2e63ce189d83b20c19aa0d1f6b3be83 pid=677 runtime=io.containerd.runc.v2
time="2023-04-07T11:08:52.410877322Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-07T11:08:52.410961162Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-07T11:08:52.410975002Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-07T11:08:52.411700924Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/d71b72afa7e384b6ef08b79ed355b652507152162da3df36b4143896872a9fb9 pid=786 runtime=io.containerd.runc.v2
time="2023-04-07T11:08:52.465844639Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-07T11:08:52.465919039Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-07T11:08:52.465931759Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-07T11:08:52.466161200Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/ed621a3fb2d045815fd1f5905afad039fa2b0f8f01aa25f62317639a95b7bb8e pid=845 runtime=io.containerd.runc.v2
time="2023-04-07T11:08:52.475443620Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-04-07T11:08:52.475725940Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-04-07T11:08:52.475866661Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-04-07T11:08:52.476157341Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/0cca3d3d13f14de07c4983a8a5a35b826da3fd23deebdc595d5a6474f4b5a58a pid=844 runtime=io.containerd.runc.v2
```

**Comment by thelamer** [comment]
So just out of curiosity how are you hitting localhost on an Oracle instance? Just trying to understand the network topology here.

**Comment by red-avtovo** [comment]
Sure, makes sense to clarify that as well. I do the SSH tunneling for now, but was planning to have a reverse proxy in the future.
I execute the command
```
ssh user@host -L8080:localhost:3000 -L8443:localhost:8443
```

After that, I can clearly see the wizard UI under https://localhost:8080 but unfortunately no workspace UI under https://localhost:8443

**Comment by thelamer** [comment]
I won't have oracle access until Monday to test, but I have tested on a board and an AWS instance and it does work. 

Have you considered opening the 8443 port to the instance to the world to test a direct connection?

**Comment by red-avtovo** [comment]
In this case I receive a general connection error
<img width="736" alt="image" src="https://user-images.githubusercontent.com/10682826/230763400-5023f1b9-be86-412b-ac48-8e7b73295e50.png">

**Comment by red-avtovo** [comment]
In this case I receive a general connection error
<img width="748" alt="Screenshot 2023-04-09 at 10 53 09" src="https://user-images.githubusercontent.com/10682826/230763455-cd0b5999-2b84-4282-8c7a-a29a12fcdfc4.png">

**Comment by red-avtovo** [comment]
bump

**Comment by thelamer** [comment]
@red-avtovo sorry I still don't have a viable OCI account, but I know this all works as there are many Kasm Deployments including DinD in OCI. 
A simple test you can run is inside the container itself just run `curl -k https://localhost:8443` and see if you get a response. From there if it is up and running try the same thing host level, then add ingress rules in your OCI Security List for 8443 tcp for 0.0.0.0/0 .

**Comment by red-avtovo** [comment]
I managed to repeat the experiment and it turns out that it fails to finish the installation
```
Setting Default Listening Port as 443
Setting Default Admin Password from stdin -P
Setting Default User Password from stdin -U
Checking if docker and docker compose are installed.
Docker is installed
24.0.5 is a supported version of docker.
Docker compose is installed
2.20.2 is a supported version of docker compose
Commands docker and docker compose detected.
installing rclone docker plugin
arm64: Pulling from rclone/docker-volume-rclone
Digest: sha256:788f086b53ad844c4308003731234d97b5ada02c33c7fcf83a8848ff5e30a591
97d37256017a: Waiting
97d37256017a: Pulling fs layer
97d37256017a: Complete
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/docker-plugins/rclone/config" to rootfs at "/data/config": stat /var/lib/docker-plugins/rclone/config: no such file or directory: unknown
An error has occurred please review the log at ./kasm_install_1692474578.log
```

docker logs -f kasm
```
...
-----
[custom-init] No custom files found, skipping...
[ls.io-init] done.
time="2023-08-19T19:48:57.922185766Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
time="2023-08-19T19:49:43.438813603Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-08-19T19:49:43.438877643Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-08-19T19:49:43.438887603Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-08-19T19:49:43.439134244Z" level=info msg="starting signal loop" namespace=plugins.moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/plugins.moby/5691b0652435792885aa9e4c3f57f47e1195fbdcd9f6d24ca9355cd355350d4f pid=505 runtime=io.containerd.runc.v2
time="2023-08-19T19:49:43.489741443Z" level=error msg="copy shim log" error="read /proc/self/fd/13: file already closed"
time="2023-08-19T19:49:43.493626775Z" level=error msg="Handler for POST /v1.43/plugins/rclone:latest/enable returned error: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/var/lib/docker-plugins/rclone/config\" to rootfs at \"/data/config\": stat /var/lib/docker-plugins/rclone/config: no such file or directory: unknown"
```

docker inspect -f '{{ index .Config.Labels "build_version" }}' kasm
Linuxserver.io version:- 1.14.0.56b9e3-ls174 Build-date:- 2023-08-19T11:35:16+00:00

docker inspect -f '{{ index .Config.Labels "build_version" }}' lscr.io/linuxserver/kasm:develop
Linuxserver.io version:- 1.14.0.56b9e3-ls174 Build-date:- 2023-08-19T11:35:16+00:00

cat /wizard/kasm_install_1692474578.log
```
root@e6ea56590692:/var/log# cat /wizard/kasm_install_1692474578.log
Setting Default Listening Port as 443
Setting Default Admin Password from stdin -P
Setting Default User Password from stdin -U
Checking if docker and docker compose are installed.
Docker is installed
24.0.5 is a supported version of docker.
Docker compose is installed
2.20.2 is a supported version of docker compose
Commands docker and docker compose detected.
installing rclone docker plugin
arm64: Pulling from rclone/docker-volume-rclone
Digest: sha256:788f086b53ad844c4308003731234d97b5ada02c33c7fcf83a8848ff5e30a591
97d37256017a: Waiting
97d37256017a: Pulling fs layer
97d37256017a: Complete
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/docker-plugins/rclone/config" to rootfs at "/data/config": stat /var/lib/docker-plugins/rclone/config: no such file or directory: unknown
An error has occurred please review the log at ./kasm_install_1692474578.log
```

After restarting the wizard page I can repeat the installation process which goes sligtly further and fails with the following:
```
...
Replacing: (${uuid:group_setting_id:1017}) with (a4fc8ef6-049f-4833-bf30-db64f5e15c0f)
Replacing: (${uuid:group_setting_id:48}) with (460aa172-611f-43ff-98b1-7afdd183c3a5)
Replacing: (${uuid:group_setting_id:43}) with (cb663f02-37f4-49e5-8e46-0f9279d86a86)
Replacing: (${uuid:group_setting_id:1009}) with (453e1096-c5d1-4586-9f2d-a237ed69dc4b)
2023-08-19 19:57:18,175 [INFO] root: Complete
Replacing: (${uuid:group_setting_id:22}) with (30191473-8eef-4597-9965-a2ec4f4a0289)
Replacing: (${uuid:group_setting_id:27}) with (4593df4b-0152-4769-a279-0db39dd7d201)
Replacing: (${uuid:group_setting_id:14}) with (71ee27ad-4dfa-4332-9c03-0154754b4e0c)
Replacing: (${uuid:group_setting_id:1026}) with (0f5b0fc6-aac7-4a8f-b4dc-d82ecab3321f)
Replacing: (${uuid:group_setting_id:1021}) with (7a29095d-faba-4de5-b53e-c7037179918c)
Replacing: (${datetime:utcnow}) with (2023-08-19 19:57:17.918137)
 Container kasm_db  Stopping
 Container kasm_db  Stopped
Database Initialization Complete
Setting Seed file as /opt/kasm/1.14.0/conf/database/seed_data/default_images_arm64.yaml
 Container kasm_db  Stopping
 Container kasm_db  Stopped
 Container kasm_db  Creating
 Container kasm_db  Created
 Container kasm_db  Starting
 Container kasm_db  Started
 Container kasm_db  Waiting
 Container kasm_db  Healthy
2023-08-19 19:57:50,954 [INFO] root: Performing Database Connectivity Test
Traceback (most recent call last):
  File "server.py", line 239, in <module>
  File "initialize_postgres_db.py", line 195, in populate_production
TypeError: argument of type 'bool' is not iterable
[1] Failed to execute script 'server' due to unhandled exception!
```

After I restart the wizard page it no longer offers me the installation, but rather shows the status page.
The workspace web ui doesn't open
