### ISSUE TITLE
[BUG] failed to create shim task

### ISSUE THREAD

**Issue by jon4sweber** [linuxserver/docker-kasm#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Kasm workspaces do not start due to an unknown Error.

### Steps To Reproduce

everytime when trying to start a kasm workspace

### Environment

```markdown
- OS: alpine 3.18
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
      - DOCKER_HUB_USERNAME=USER #optional
      - DOCKER_HUB_PASSWORD=PASS #optional
      - DOCKER_MTU=1500 #optional
    volumes:
      - /path/to/data:/opt
      - /path/to/profiles:/profiles #optional
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped
```

### Container logs

```bash
(Exception creating Kasm: Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.43/containers/bc751be32625b0279093a617838490b287d2e057f8268b072590e0ddf1c04072/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__init__.py", line 539, in post
  File "provision.py", line 1547, in provision
  File "provision.py", line 1539, in provision
  File "docker/models/containers.py", line 818, in run
  File "docker/models/containers.py", line 404, in start
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/container.py", line 1111, in start
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.43/containers/bc751be32625b0279093a617838490b287d2e057f8268b072590e0ddf1c04072/start: Internal Server Error ("failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: cannot enter cgroupv2 "/sys/fs/cgroup/docker" with domain controllers -- it is in threaded mode: unknown")
```

**Comment by thelamer** [comment]
I have never tested DinD like this on an Alpine host, the error seems to indicate that Docker is not running inside of the container properly. Do other DinD container work properly on an Alpine host? (keep in mind this one is Jammy based as well)

**Comment by jon4sweber** [comment]
Thanks for the reply!
I do have a jupyterlab, swag, freecad and webtop container running on the same host. The deployment with kasm has worked before. unfortunately i cannot specify if an alpine or kasm update broke it.

**Comment by thelamer** [comment]
When I say DinD container I am referring to stuff like this https://hub.docker.com/_/docker where you run a container with it's own docker runtime in privileged mode.
