### ISSUE TITLE
[BUG] < dev/dri/renderD129 >

### ISSUE THREAD

**Issue by nikhil96widhani** [linuxserver/docker-kasm#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installed KASM using docker, Mounted dri volume. I have 2 entried in the dri card1 and renderD129. Selected card1 dusing install but everytime i see logging it has this error "error gathering device information while adding custom device "/dev/dri/renderD129": no such file or directory". this might be because on my host its d128 instead of d129. 

### Expected Behavior

There should not be such error and renderd128 should be used instead of d129 as its not present

### Steps To Reproduce

use a fresh install

### Environment

```markdown
- OS: Ununtu server 24
- How docker service was installed: Docker.io with linuxserver docker image
```

### CPU architecture

x86-64

### Docker creation

```bash
#portainer with docker compose
version: "2.1"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    devices:
      - "/dev/dri/card1:/dev/dri/card1"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    environment:
      - TZ=America/Toronto
      - KASM_PORT=4443
#      - DOCKER_HUB_USERNAME=USER #optional
#      - DOCKER_HUB_PASSWORD=PASS #optional
#      - DOCKER_MTU=1500 #optional
    volumes:
      - ~/volumes/kasm/opt:/opt
      - ~/volumes/kasm/profiles:/profiles
      - /dev/dri:/dev/dri
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3001:3000
      - 4443:4443
    restart: unless-stopped
```

### Container logs

```bash
host: b8bfb798d528
ingest_date: 202405131400
application: kasm_api
levelname: ERROR
kasm_user_name: admin@kasm.local
process: client_api_server
client_ip: 192.168.0.11
user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15
message
Error during Create request for Server(4aae7f16-0a63-4c74-b09a-f64ce7ab406f) : (Exception creating Kasm: Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.45/containers/3b05fc8de49c7218f9b5747ae4bfc9db64c5bb847a558833c1bc31ecfea3da06/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__init__.py", line 573, in post
  File "provision.py", line 1871, in provision
  File "provision.py", line 1863, in provision
  File "docker/models/containers.py", line 818, in run
  File "docker/models/containers.py", line 404, in start
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/container.py", line 1111, in start
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.45/containers/3b05fc8de49c7218f9b5747ae4bfc9db64c5bb847a558833c1bc31ecfea3da06/start: Internal Server Error ("error gathering device information while adding custom device "/dev/dri/renderD129": no such file or directory")
)
```

**Comment by inquam** [comment]
I run into the same issue with an nvidia gpu installed and the nvidia docker runtime working fine for other containers in my setup.
