### ISSUE TITLE
[BUG] Kasm OpenID "Internal Error" after successful login on keycloak

### ISSUE THREAD

**Issue by Illisen** [linuxserver/docker-kasm#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As i try loging to kasm via keycloak, when it does back to "/api/oidc_callback" it always goes in an "Internal error"

### Expected Behavior

After successful login with keycloak, should correctly login to kasm.

### Steps To Reproduce

Kasm 1.15.0.577587

kasm openid config:
<img width="143" alt="image" src="https://github.com/user-attachments/assets/8e18e62a-ee4d-4b7e-bab7-bcd50f1ae15e">

Can provide my keycloak client config if needed.

### Environment

```markdown
- OS: Debian 11
- How docker service was installed: using debian native package manager
- Kasm and keycloak behind nginx reverse proxy
```

### CPU architecture

x86-64

### Docker creation

```bash
using docker-compose.yml :

services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=xxxx
    volumes:
      - ./opt:/opt
      - ./profiles:/profiles
    ports:
      - 3000:3000
      - xxxx:xxxx
    restart: unless-stopped
```

### Container logs

```bash
No logs appear in docker logs but i got this in kasm dashboard :

host: 30df5536a209
ingest_date: 202409160957
application: kasm_api
levelname: ERROR
process: root
client_ip: 13.41.193.200, 192.168.224.1
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 OPR/113.0.0.0
message
Unhandled exception occurred
Traceback (most recent call last):
  File "requests/models.py", line 971, in json
  File "simplejson/__init__.py", line 518, in loads
  File "simplejson/decoder.py", line 370, in decode
  File "simplejson/decoder.py", line 400, in raw_decode
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cherrypy/_cprequest.py", line 628, in respond
  File "cherrypy/_cprequest.py", line 687, in _do_respond
  File "cherrypy/lib/encoding.py", line 219, in __call__
  File "cherrypy/_cpdispatch.py", line 54, in __call__
  File "utils.py", line 99, in wrapper
  File "client_api.py", line 952, in oidc_callback
  File "authentication/oidc/__init__.py", line 132, in process_callback
  File "requests/models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
```

**Comment by Illisen** [comment]
Okay, after multiple failed attemps, it would seem I was simply missing the 'openid' field in the scope...
